### PR TITLE
Refactor events

### PR DESCRIPTION
**Pull request by sparrell**
add noop events for unused powerups

### CODE REVIEW

**Comment by sigu** [comment]
Conflicts with the changes I have just merged in, needs to be resolved

**Comment by sparrell** [comment]
@sigu: conflicts resolved. I still haven't gotten the hang of when to base a branch off another branch to minimize conflicts.

**Comment by sigu** [comment]
The current release candidate branch should be the base branch for new features since we are ultimately going to merge into it

**Review by sigu — APPROVED** [review]

**Comment by sigu** [comment]
I will wait for a review from @TraceyOnim and/ or @WanjikuMac before merging this in

**Comment by sparrell** [comment]
I'm jumping the gun and merging in so can have in the demo .5 coming out

**Pull request merged**
