### PR TITLE
Bc qna

### PR DESCRIPTION
**Pull request by StickyFloors**
First Briar Cutter question amended to QNA as 003g.md

### CODE REVIEW

**Review by sparrell — CHANGES_REQUESTED** [review]
I'm on ipad - I'll clean this up when on laptop. I'll reconcile the instructions and clean the questions conflicts

**Review by sparrell — APPROVED** [review]

**Review by sparrell — CHANGES_REQUESTED** [review]
trying to figure out how to resolve the conflicts

**Comment by sparrell** [comment]
One issue is that the PR is attempting to modify a file that is not there anymore. The quadquizaminos/instructrions.ex file is no longer in _web directory. It. is now in the quadquizaminos directory. This isn't fixable with a web edit and will be changed in command line

**Comment by StickyFloors** [comment]
I think the long and the short of it is that I should re-fork from the
current working branch, resubmit all four items and re-pull.

Thoughts?

DJ

**Comment by sparrell** [comment]
PR #225 and PR #226  replace this PR

**Pull request closed without merging**
