### PR TITLE
Move admin privileges(start/stop/create contest) to admin page

### LINKED ISSUE #477: Move admin privilege under admins page
Contest admin should be under admin button on header bar.

all admin privileges/actions to be moved to admin page

### PR DESCRIPTION
**Pull request by TraceyOnim**
closes #477 

Peek 2021-08-30 18-28

### CODE REVIEW

**Comment by WanjikuMac** [comment]
@emmyachieng this branch doesn't compile, it's throwing an error `undefined function admin?/1` could you please work on this and make sure it works. Thanks

**Comment by Japhetb** [comment]
> @emmyachieng this branch doesn't compile, it's throwing an error `undefined function admin?/1` could you please work on this and make sure it works. Thanks

On it

**Comment by Japhetb** [comment]
> @emmyachieng this branch doesn't compile, it's throwing an error `undefined function admin?/1` could you please work on this and make sure it works. Thanks

Done

**Comment by WanjikuMac** [comment]
Admin still has the ability to add contents from the contests page, @sigu @emmyachieng @Japhetb are we still supposed to have this? I am referring to the `add` button under the contests page

**Comment by WanjikuMac** [comment]
How comes I can't see rsvp ability and countdown functionality on this branch? Did we not merge those in develop?

**Comment by TraceyOnim** [comment]
Confirm if you have pulled the latest changes

**Comment by WanjikuMac** [comment]
@TraceyOnim you're right, I had not pulled, everything else looks good.

**Review by WanjikuMac — APPROVED** [review]

**Pull request merged**
