### PR TITLE
Fixing dependabot cannot update nth-check to a non-vulnerable version

### PR DESCRIPTION
**Pull request by Japhetb**

### CODE REVIEW

**Comment by WanjikuMac** [comment]
@Japhetb did you change the npm package lock file?

**Comment by WanjikuMac** [comment]
I mean `package.json` and did you initially have a `package-lock.json`? Because from the diff it looks like you did not

**Comment by Japhetb** [comment]
> @Japhetb I mean `package.json` and did you initially have a `package-lock.json`? Because from the diff it looks like you did not

I had clone the project again and did not have the file

**Comment by WanjikuMac** [comment]
inside the assets folder you need to run `npm i`

**Comment by Japhetb** [comment]
> inside the assets folder you need to run `npm i`

i did that

**Pull request closed without merging**
