### PR TITLE
Select topic

### PR DESCRIPTION
**Pull request by TraceyOnim**
Peek 2021-03-03 18-25

closes #80

### CODE REVIEW

**Review by sparrell — CHANGES_REQUESTED** [review]
I believe I have the PR up and running on http://cantor.quizquadblocks.sfractal.com:4000. 
It has an error. You and go to it and reproduce this error

When I hit space bar it goes back to home screen. Looking at logs, I see:
 (File.Error) could not list directory \"qna\": no such file or directory

doing a find on vm, I find qna does exist (but look at path, more later) eg:
./prod/rel/quadquizaminos/lib/quadquizaminos-0.3.3/priv/static/qna/sbom/102.md

getting into iex, and running Application.get_env(:quadquizaminos, :qna_directory)
 (the @qna_directory at begining of qna module) yields:
iex(quadquizaminos@cantor)1> Application.get_env(:quadquizaminos, :qna_directory)
"/home/app/prod/lib/quadquizaminos/priv/static/qna"

Note the code is using ...quadquizaminos... and the actual is ...quadquizaminos-0.3.3...

**Comment by TraceyOnim** [comment]
I have been able to reproduce the same error by running docker locally. It's not finding "qna" folder inside the container. I have realized the branch is not updated with some changes in main.

**Comment by TraceyOnim** [comment]
@sparrell I have worked on the fix

**Review by sparrell — APPROVED** [review]
seems fixed

**Comment by sparrell** [comment]
tried on cantor and looks good

**Pull request merged**
