### PR TITLE
add bottom vulnerability on any wrong answer

### LINKED ISSUE #109: add bottom vulnerability on any wrong answer
whenever any question is answered wrong, mark a random 'bottom' block with either a license issue or a vulnerability.
to find which block to mark, do whatever is easy to implement of (a) picking at random (b) picking leftmost, lowest block. Do not pick empty spaces, do not pick blocks  that already are marked with any of vuln, lic, attack, lawsuit

### PR DESCRIPTION
**Pull request by TraceyOnim**
closes #109 

Peek 2021-04-06 14-37

### CODE REVIEW

**Comment by WanjikuMac** [comment]
@TraceyOnim After a vulnerability has been added, shouldn't the game continue? It remains paused on my end

**Comment by TraceyOnim** [comment]
> @TraceyOnim After a vulnerability has been added, shouldn't the game continue? It remains paused on my end

The reason to make it stay in paused state is to let the player know easily a vulnerability is added after a wrong answer. But we can confirm with @sparrell first

**Comment by WanjikuMac** [comment]
okay, everything else looks good to me

**Comment by sigu** [comment]
How do I continue playing after seeing the paused state?

**Comment by TraceyOnim** [comment]
> How do I continue playing after seeing the paused state?

by clicking the space bar there is a continue button on the pop up window which will allow the player to continue playing

**Review by sigu — APPROVED** [review]

**Pull request merged**
