### PR TITLE
upgrade phoenix and liveview

### PR DESCRIPTION
**Pull request by sigu**

### CODE REVIEW

**Comment by WanjikuMac** [comment]
@sigu contests don't show up when you switch to mobile mode, under `/contests` and for `/admin/contests` too. 

On the questions modal, there is a category called `0START` is that by design?

**Review by WanjikuMac — COMMENTED** [review]
@sigu contests don't show up when you switch to mobile mode, under /contests and for /admin/contests too.

On the questions modal, there is a category called 0START is that by design?

**Comment by TraceyOnim** [comment]
> I just messed up this branch @TraceyOnim please force push your changes

@sigu , I have forced push my changes

**Comment by WanjikuMac** [comment]
@TraceyOnim  under the `/contests` and `admin/contests` pages while in mobile view, I still can't see the contests. Also there are a bunch of warnings, I have attached a screenshot
Screenshot 2022-07-13 at 12 26 23

**Comment by TraceyOnim** [comment]
> @TraceyOnim under the `/contests` and `admin/contests` pages while in mobile view, I still can't see the contests. Also there are a bunch of warnings, I have attached a screenshot Screenshot 2022-07-13 at 12 26 23

@WanjikuMac I have fixed the issue with the contest page.
However, I'm not seeing the warnings in my terminal which elixir version are you using ?

**Comment by WanjikuMac** [comment]
@TraceyOnim The new changes look okay I can view the contests both on web and mobile, but one can't successfully edit the contest date of an already created contest. Should we open a separate issue for this?

**Comment by TraceyOnim** [comment]
> @TraceyOnim The new changes look okay I can view the contests both on web and mobile, but one can't successfully edit the contest date of an already created contest. Should we open a separate issue for this?

Lets open another PR for this . Though on my end it works . @sigu confirm on your end if you can edit contest date

**Pull request merged**
